language: node_js
node_js: "14"
os:
  - win
cache: yarn

install:
  - npm install -g yarn
  - yarn install

scripts:
  - yarn build


deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  local_dir: dist
  file_glob: true
  file:
    - "dist/*.exe"
    - "dist/*.deb"
    - "dist/*.dmg"
  on:
    branch: master
    tags: true