language: node_js
node_js: "14"
cache: yarn

install:
  - npm install -g yarn
  - yarn install

scripts:
  - yarn build


deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: "./dist/*"
  on:
    branch: master