language: node_js
node_js: "14"
cache: yarn

install:
  - npm install -g yarn
  - yarn install

scripts:
  - yarn test
  - yarn build


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master